# Amazon ML Challenge 2026 — Track 03: Scalable Candidate Generation (Blocking)
**Objective:** Reduce the combinatorial comparison space from $O(N \times M)$ (~22.4 Trillion pairs) to a high-recall candidate set.
- 1. Country-partitioned candidate filtering
- 2. Standard rule-based blocking keys
- 3. Inverted index token blocking with IDF weighting
- 4. Candidate count distribution per query (mean, median, p90, max)
- 5. Generating candidate pairs for downstream matching

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 01. SETUP & PATH VERIFICATION
# ============================================================
from pathlib import Path
import pandas as pd
import os
REPO = Path("/content/Amazon-ML-Challenge-2026")
NORMALIZED_DIR = REPO / "outputs" / "person1_step1" / "normalized"
TRAIN_DIR = REPO / "data" / "train"
TEST_DIR = REPO / "data" / "test"
print("REPO:", REPO)
print("Normalized directory:", NORMALIZED_DIR)
print("\n===== NORMALIZED FILES =====")
for f in sorted(NORMALIZED_DIR.glob("*.tsv")):
    size_mb = f.stat().st_size / (1024**2)
    print(f"{f.name:<40} {size_mb:>8.2f} MB")
print("\n===== TRAIN FILES =====")
for f in sorted(TRAIN_DIR.glob("*")):
    print(f.name)
print("\n===== TEST FILES =====")
for f in sorted(TEST_DIR.glob("*")):
    print(f.name)

REPO: /content/Amazon-ML-Challenge-2026
Normalized directory: /content/Amazon-ML-Challenge-2026/outputs/person1_step1/normalized

===== NORMALIZED FILES =====
test_source1_normalized.tsv                  0.00 MB
test_source2_normalized.tsv                  0.00 MB
test_source3_normalized.tsv                  0.00 MB
train_source1_normalized.tsv                 0.00 MB
train_source2_normalized.tsv                 0.00 MB
train_source3_normalized.tsv                 0.00 MB

===== TRAIN FILES =====
train_ground_truth.tsv.part_aa
train_ground_truth.tsv.part_ab
train_source1.tsv.part_aa
train_source1.tsv.part_ab
train_source1.tsv.part_ac
train_source2.tsv.part_aa
train_source2.tsv.part_ab
train_source2.tsv.part_ac
train_source2.tsv.part_ad
train_source2.tsv.part_ae
train_source2.tsv.part_af
train_source3.tsv.part_aa
train_source3.tsv.part_ab
train_source3.tsv.part_ac
train_source3.tsv.part_ad
train_source3.tsv.part_ae
train_source3.tsv.part_af

===== TEST FILES =====
test_source1.tsv.part_aa
test_source1.tsv.part_ab
test_source2.tsv.part_aa
test_source2.tsv.part_ab
test_source2.tsv.part_ac
test_source2.tsv.part_ad
test_source2.tsv.part_ae
test_source2.tsv.part_af
test_source3.tsv.part_aa
test_source3.tsv.part_ab
test_source3.tsv.part_ac
test_source3.tsv.part_ad
test_source3.tsv.part_ae
test_source3.tsv.part_af

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 02. VERIFY NORMALIZED FILES + SAMPLE DATA
# ============================================================

from pathlib import Path
import pandas as pd

REPO = Path("/content/Amazon-ML-Challenge-2026")
NORMALIZED_DIR = REPO / "outputs" / "person1_step1" / "normalized"

files = sorted(NORMALIZED_DIR.glob("*_normalized.tsv"))

print("===== EXACT FILE SIZES =====")

for f in files:
    size_bytes = f.stat().st_size
    size_mb = size_bytes / (1024**2)

    print(f"{f.name}")
    print(f"  bytes : {size_bytes:,}")
    print(f"  MB    : {size_mb:.4f}")

print("\n===== SAMPLE + SCHEMA CHECK =====")

for f in files:
    print(f"\n--- {f.name} ---")

    df = pd.read_csv(
        f,
        sep="\t",
        nrows=5,
        dtype=str,
        keep_default_na=False
    )

    print("Columns:", df.columns.tolist())
    print("Rows loaded:", len(df))
    print(df.to_string(index=False))

===== EXACT FILE SIZES =====
test_source1_normalized.tsv
  bytes : 134
  MB    : 0.0001
test_source2_normalized.tsv
  bytes : 134
  MB    : 0.0001
test_source3_normalized.tsv
  bytes : 134
  MB    : 0.0001
train_source1_normalized.tsv
  bytes : 134
  MB    : 0.0001
train_source2_normalized.tsv
  bytes : 134
  MB    : 0.0001
train_source3_normalized.tsv
  bytes : 134
  MB    : 0.0001

===== SAMPLE + SCHEMA CHECK =====

--- test_source1_normalized.tsv ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows loaded: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:f6ce8790347d7db75fcac8405d9e7817b54fe653a97865b40163f919425049f4
                                                             size 174998099

--- test_source2_normalized.tsv ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows loaded: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:5bc01f5e54f63137c122e11bebf5971a7d30e71f0ada7b51683a34a6723b7a96
                                                             size 491148398

--- test_source3_normalized.tsv ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows loaded: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:58ef93ced22f8badcc9e89425679378158206e70f382aa3961c66d9f46ed58f4
                                                             size 493709014

--- train_source1_normalized.tsv ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows loaded: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:05d53a5d74bd3505c9fd559fb8c18c42e2256107571d62c6d22c3beb4245e1b9
                                                             size 210044643

--- train_source2_normalized.tsv ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows loaded: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:a637b672ee43b7bd37411421e092b36dda40328a5d81c55059c540663e82dbd6
                                                             size 473461005

--- train_source3_normalized.tsv ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows loaded: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:13fbd7561fa1422fdb7a5f3c175843c9ec9d2428fb838fc15d7cd9c959470287
                                                             size 492985040

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 03A. INSTALL GIT LFS
# ============================================================

!apt-get update -qq
!apt-get install -y git-lfs -qq
!git lfs install

%cd /content/Amazon-ML-Challenge-2026

!git lfs version

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package git-lfs.
(Reading database ... 122809 files and directories currently installed.)
Preparing to unpack .../git-lfs_3.4.1-1ubuntu0.4_amd64.deb ...
Unpacking git-lfs (3.4.1-1ubuntu0.4) ...
Setting up git-lfs (3.4.1-1ubuntu0.4) ...
Processing triggers for man-db (2.12.0-4build2) ...
Updated Git hooks.
Git LFS initialized.
/content/Amazon-ML-Challenge-2026
git-lfs/3.4.1 (GitHub; linux amd64; go 1.22.2)

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 03B. DOWNLOAD NORMALIZED DATA FROM LFS
# ============================================================

%cd /content/Amazon-ML-Challenge-2026

!git lfs pull --include="outputs/person1_step1/normalized/*"

/content/Amazon-ML-Challenge-2026

In [ ]:
from pathlib import Path

NORMALIZED_DIR = Path(
    "/content/Amazon-ML-Challenge-2026/outputs/person1_step1/normalized"
)

print("===== NORMALIZED FILES =====")

for f in sorted(NORMALIZED_DIR.glob("*.tsv")):
    size_mb = f.stat().st_size / (1024**2)
    print(f"{f.name:<40} {size_mb:>10.2f} MB")

===== NORMALIZED FILES =====
test_source1_normalized.tsv                  166.89 MB
test_source2_normalized.tsv                  468.40 MB
test_source3_normalized.tsv                  470.84 MB
train_source1_normalized.tsv                 200.31 MB
train_source2_normalized.tsv                 451.53 MB
train_source3_normalized.tsv                 470.15 MB

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 04. INSPECT NORMALIZED DATA
# ============================================================

from pathlib import Path
import pandas as pd

REPO = Path("/content/Amazon-ML-Challenge-2026")
NORMALIZED_DIR = REPO / "outputs" / "person1_step1" / "normalized"

TRAIN_FILES = {
    "source1": NORMALIZED_DIR / "train_source1_normalized.tsv",
    "source2": NORMALIZED_DIR / "train_source2_normalized.tsv",
    "source3": NORMALIZED_DIR / "train_source3_normalized.tsv",
}

for source, path in TRAIN_FILES.items():

    print("\n" + "=" * 80)
    print(f"TRAIN {source.upper()}")
    print("=" * 80)

    df = pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        nrows=10
    )

    print("Columns:", df.columns.tolist())
    print("Sample rows:")
    print(df.to_string(index=False))

================================================================================
TRAIN SOURCE1
================================================================================
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample rows:
   entity_id                            business_name                                                                                                          business_address country
S1-925783039                      orelee's barbershop                                                                                    1795 westchester drive, high point, nc      US
S1-773889195                              prime money                                                                                           17560 ellis road, tahlequah, ok      US
S1-377745466                            b+ retail inc                                                                                       1712 montebello avenue, phoenix, az      US
S1-133037285                            christ chapel                                                                         2100 cameron drive, unit apartment g, dundalk, md      US
S1-755362802                  prabhav business center                                                                      797, lake town block a, kolkata, howrah, west bengal   INDIA
S1-851869949               custom wealth services llc                                                                                         oh, columbus, 5559 orville avenue      US
S1-785847572 consulting nyasa nursing private limited 2505, tower 1, oakwood, runwal greens, mulund goreagon link road, near fortis hospital, bhandup west, mumbai, maharashtra   INDIA
 S1-27541239                        nexus anchor rain                                                                              1111 church street, unit 2007, nashville, tn      US
S1-629417405                        moore bitwise inc                                                                                     337 oakland avenue, michigan city, in      US
 S1-22305073               dermatology green medicine                                                               294 meadowcreek drive, unit unit 2, village of pewaukee, wi      US

================================================================================
TRAIN SOURCE2
================================================================================
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample rows:
   entity_id                                                          business_name                                                           business_address country
S2-166376419                                         र म म र क ट ग प र इव ट ल म ट ड                               kh no. -570/13, new delhi, west delhi, delhi   INDIA
S2-764573417                                           -- holloway peak inc seafood                                                  105 elm st, morganton, nc      US
S2-639257739                                                आद त य प र पर ट ज एलएलप                           g-3/571, gulmohar colony, bhopal, madhya pradesh   INDIA
S2-163963287                                                             summit inc                                      greensboro, nc, 19 1/2 stardust trail      US
 S2-49942811                                           delta tetlecommunication inc                                            914 pierpont ave, cleveland, oh      US
S2-138046867                                                         lee and lawson                                    1702 pine avenue, city of menomonie, wi      US
S2-584977605 shivshakti vidyalaya vidyalaya overseas corporation www.shivshakti.com                                 h.no 204 c road hoshiarpur, punjab, punjab   INDIA
S2-277444929                                             shree infracon private ltd 63/2275/7, alhind tower, first floor, jafferkhan colony, kozhikode, kerala   INDIA
S2-721031885                                           chavira platinum chimera llc                                         282 saxony drive, ftt mitchell, ky      US
S2-508602797                                foundation excel agency private limited                   hn 753 e-1, bharat nagar, 104/1/1 erandwane, maharashtra   INDIA

================================================================================
TRAIN SOURCE3
================================================================================
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample rows:
   entity_id                               business_name                                                                            business_address country
S3-202863386                          wilfordhancock.com                                                                 mack rd, haltom city, texas      US
S3-859268022 international south consultants private ltd                                                                                               INDIA
 S3-22467283                 llc moncada léarning center                                                             5780 fawn ct, fort worth, texas      US
S3-671162755                              moyna's coffee                                                1 ivanhoe ave, po box 6009, cincinnati, ohio      US
S3-960981775                pvt. efs print ventures ltd. door no 183, 41st cross, 22nd main 9th block jayanagar, bengaluru urban, bangalore, ಕರ ನ ಟಕ   INDIA
S3-578159284              llc hernandez colonial redwood                                   2260- housecreek trail, unit 407, raleigh, north carolina      US
S3-121412624               classic equity partners group                                        6885 catalpa bluff ln, po box 5799, dickinson, texas      US
S3-249416830              ectolumdrex dba x+ madison inc                                                        s03575 cty tk m, town of buffalo, wi      US
S3-107644605                     animal hanisch hospirlg                                           ##8 willow oak lane, fl. 0, saint louis, missouri      US
S3-160217003                               gomez optimal                                                           343 hempstead 161, hope, arkansas      US

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 05. BLOCKING KEY SELECTIVITY ANALYSIS
# ============================================================

from pathlib import Path
import pandas as pd
import re
import numpy as np

REPO = Path("/content/Amazon-ML-Challenge-2026")
NORMALIZED_DIR = REPO / "outputs" / "person1_step1" / "normalized"

TRAIN_FILES = {
    "source1": NORMALIZED_DIR / "train_source1_normalized.tsv",
    "source2": NORMALIZED_DIR / "train_source2_normalized.tsv",
    "source3": NORMALIZED_DIR / "train_source3_normalized.tsv",
}

# ------------------------------------------------------------
# Blocking-key functions
# ------------------------------------------------------------

def add_blocking_keys(df):

    name = df["business_name"].fillna("").astype(str)
    address = df["business_address"].fillna("").astype(str)
    country = df["country"].fillna("").astype(str)

    # First whitespace-delimited token
    name_token1 = name.str.split().str[0].fillna("")

    # First 4 Unicode characters
    name_prefix4 = name.str[:4]

    # Leading house/building number, if present
    house_number = address.str.extract(
        r"^\s*([0-9]+[A-Za-z]?)",
        expand=False
    ).fillna("")

    df = df.copy()

    df["block_name_exact"] = (
        country + "|" + name
    )

    df["block_name_prefix4"] = (
        country + "|" + name_prefix4
    )

    df["block_name_token1"] = (
        country + "|" + name_token1
    )

    df["block_address_exact"] = (
        country + "|" + address
    )

    df["block_address_house"] = (
        country + "|" + house_number
    )

    return df


# ------------------------------------------------------------
# Process each source in chunks
# ------------------------------------------------------------

BLOCKING_KEYS = [
    "block_name_exact",
    "block_name_prefix4",
    "block_name_token1",
    "block_address_exact",
    "block_address_house",
]

all_stats = []

for source, path in TRAIN_FILES.items():

    print("\n" + "=" * 80)
    print(f"ANALYSING {source.upper()}")
    print("=" * 80)

    # Store only key counts, NOT the full dataset
    key_counts = {
        key: {}
        for key in BLOCKING_KEYS
    }

    total_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=200_000
    ):

        total_rows += len(chunk)

        chunk = add_blocking_keys(chunk)

        for key in BLOCKING_KEYS:

            counts = chunk[key].value_counts()

            for value, count in counts.items():

                if value == "|" or value.endswith("|"):
                    continue

                key_counts[key][value] = (
                    key_counts[key].get(value, 0) + int(count)
                )

    print(f"Rows analysed: {total_rows:,}")

    for key in BLOCKING_KEYS:

        counts = pd.Series(key_counts[key], dtype="int64")

        if len(counts) == 0:
            continue

        # Number of non-empty blocks
        n_blocks = len(counts)

        # Rows participating in a block
        rows_in_blocks = int(counts.sum())

        # Cross-pair count within blocks
        pair_count = int((counts * (counts - 1) // 2).sum())

        print(f"\n{key}")
        print(f"  blocks              : {n_blocks:,}")
        print(f"  rows in blocks      : {rows_in_blocks:,}")
        print(f"  largest block      : {int(counts.max()):,}")
        print(f"  median block size  : {counts.median():.1f}")
        print(f"  mean block size    : {counts.mean():.2f}")
        print(f"  internal pairs     : {pair_count:,}")

        all_stats.append({
            "source": source,
            "blocking_key": key,
            "rows": total_rows,
            "blocks": n_blocks,
            "largest_block": int(counts.max()),
            "median_block_size": float(counts.median()),
            "mean_block_size": float(counts.mean()),
            "internal_pairs": pair_count,
        })

stats_df = pd.DataFrame(all_stats)

print("\n" + "=" * 80)
print("SUMMARY")
print("=" * 80)

display(
    stats_df.sort_values(
        ["blocking_key", "source"]
    ).reset_index(drop=True)
)

================================================================================
ANALYSING SOURCE1
================================================================================
Rows analysed: 2,206,821

block_name_exact
  blocks              : 1,537,868
  rows in blocks      : 2,206,821
  largest block      : 253
  median block size  : 1.0
  mean block size    : 1.43
  internal pairs     : 8,403,225

block_name_prefix4
  blocks              : 77,084
  rows in blocks      : 2,206,821
  largest block      : 15,080
  median block size  : 3.0
  mean block size    : 28.63
  internal pairs     : 2,293,434,405

block_name_token1
  blocks              : 137,112
  rows in blocks      : 2,206,821
  largest block      : 15,058
  median block size  : 3.0
  mean block size    : 16.10
  internal pairs     : 1,793,681,954

block_address_exact
  blocks              : 2,130,606
  rows in blocks      : 2,206,821
  largest block      : 14
  median block size  : 1.0
  mean block size    : 1.04
  internal pairs     : 153,051

block_address_house
  blocks              : 48,558
  rows in blocks      : 1,365,849
  largest block      : 7,969
  median block size  : 3.0
  mean block size    : 28.13
  internal pairs     : 461,340,077

================================================================================
ANALYSING SOURCE2
================================================================================
Rows analysed: 5,034,616

block_name_exact
  blocks              : 4,157,079
  rows in blocks      : 5,034,610
  largest block      : 476
  median block size  : 1.0
  mean block size    : 1.21
  internal pairs     : 7,068,375

block_name_prefix4
  blocks              : 156,384
  rows in blocks      : 5,034,610
  largest block      : 39,808
  median block size  : 2.0
  mean block size    : 32.19
  internal pairs     : 11,608,601,814

block_name_token1
  blocks              : 484,518
  rows in blocks      : 5,034,610
  largest block      : 39,419
  median block size  : 1.0
  mean block size    : 10.39
  internal pairs     : 11,120,644,569

block_address_exact
  blocks              : 4,300,082
  rows in blocks      : 4,865,649
  largest block      : 19
  median block size  : 1.0
  mean block size    : 1.13
  internal pairs     : 743,940

block_address_house
  blocks              : 97,705
  rows in blocks      : 2,567,689
  largest block      : 13,242
  median block size  : 3.0
  mean block size    : 26.28
  internal pairs     : 1,367,863,581

================================================================================
ANALYSING SOURCE3
================================================================================
Rows analysed: 5,285,603

block_name_exact
  blocks              : 4,435,343
  rows in blocks      : 5,285,585
  largest block      : 476
  median block size  : 1.0
  mean block size    : 1.19
  internal pairs     : 6,956,679

block_name_prefix4
  blocks              : 160,564
  rows in blocks      : 5,285,585
  largest block      : 49,538
  median block size  : 2.0
  mean block size    : 32.92
  internal pairs     : 13,679,308,791

block_name_token1
  blocks              : 545,738
  rows in blocks      : 5,285,585
  largest block      : 49,579
  median block size  : 1.0
  mean block size    : 9.69
  internal pairs     : 11,931,204,408

block_address_exact
  blocks              : 4,631,094
  rows in blocks      : 5,109,687
  largest block      : 29
  median block size  : 1.0
  mean block size    : 1.10
  internal pairs     : 634,798

block_address_house
  blocks              : 98,008
  rows in blocks      : 2,705,773
  largest block      : 13,900
  median block size  : 3.0
  mean block size    : 27.61
  internal pairs     : 1,517,584,380

================================================================================
SUMMARY
================================================================================

,source,blocking_key,rows,blocks,largest_block,median_block_size,mean_block_size,internal_pairs
0,source1,block_address_exact,2206821,2130606,14,1.0,1.035772,153051
1,source2,block_address_exact,5034616,4300082,19,1.0,1.131525,743940
2,source3,block_address_exact,5285603,4631094,29,1.0,1.103343,634798
3,source1,block_address_house,2206821,48558,7969,3.0,28.128197,461340077
4,source2,block_address_house,5034616,97705,13242,3.0,26.280016,1367863581
5,source3,block_address_house,5285603,98008,13900,3.0,27.607675,1517584380
6,source1,block_name_exact,2206821,1537868,253,1.0,1.434987,8403225
7,source2,block_name_exact,5034616,4157079,476,1.0,1.211093,7068375
8,source3,block_name_exact,5285603,4435343,476,1.0,1.191697,6956679
9,source1,block_name_prefix4,2206821,77084,15080,3.0,28.628782,2293434405
10,source2,block_name_prefix4,5034616,156384,39808,2.0,32.193895,11608601814
11,source3,block_name_prefix4,5285603,160564,49538,2.0,32.918867,13679308791
12,source1,block_name_token1,2206821,137112,15058,3.0,16.095025,1793681954
13,source2,block_name_token1,5034616,484518,39419,1.0,10.390966,11120644569
14,source3,block_name_token1,5285603,545738,49579,1.0,9.685206,11931204408

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 06. GROUND TRUTH STRUCTURE CHECK
# ============================================================

from pathlib import Path
import pandas as pd

REPO = Path("/content/Amazon-ML-Challenge-2026")
TRAIN_DIR = REPO / "data" / "train"

print("=" * 80)
print("GROUND TRUTH FILES")
print("=" * 80)

gt_files = sorted(TRAIN_DIR.glob("train_ground_truth*"))

for f in gt_files:
    print(f.name, f.stat().st_size / (1024**2), "MB")

print("\n" + "=" * 80)
print("GROUND TRUTH SAMPLE / SCHEMA")
print("=" * 80)

for f in gt_files:
    print(f"\n--- {f.name} ---")

    df = pd.read_csv(
        f,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        nrows=10
    )

    print("Columns:", df.columns.tolist())
    print("Rows sampled:", len(df))
    print(df.to_string(index=False))

================================================================================
GROUND TRUTH FILES
================================================================================
train_ground_truth.tsv.part_aa 0.00012683868408203125 MB
train_ground_truth.tsv.part_ab 0.00012683868408203125 MB

================================================================================
GROUND TRUTH SAMPLE / SCHEMA
================================================================================

--- train_ground_truth.tsv.part_aa ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows sampled: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:6a3b035b829ef08f4c6f9e94974fe52a7896cb8249b28788cea9a876d471f08c
                                                              size 89128960

--- train_ground_truth.tsv.part_ab ---
Columns: ['version https://git-lfs.github.com/spec/v1']
Rows sampled: 2
                                 version https://git-lfs.github.com/spec/v1
oid sha256:fe41b518ba8243dae58b3cba712e3aca5c27c21ff367dc171369fa7232c59def
                                                              size 37886623

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 07. DOWNLOAD GROUND-TRUTH DATA FROM LFS
# ============================================================

%cd /content/Amazon-ML-Challenge-2026

!git lfs pull --include="data/train/train_ground_truth.tsv.part_*"

print("\n===== GROUND TRUTH FILES AFTER LFS PULL =====")

from pathlib import Path

TRAIN_DIR = Path("/content/Amazon-ML-Challenge-2026/data/train")

for f in sorted(TRAIN_DIR.glob("train_ground_truth.tsv.part_*")):
    size_mb = f.stat().st_size / (1024**2)
    print(f"{f.name:45} {size_mb:10.2f} MB")

/content/Amazon-ML-Challenge-2026

===== GROUND TRUTH FILES AFTER LFS PULL =====
train_ground_truth.tsv.part_aa                     85.00 MB
train_ground_truth.tsv.part_ab                     36.13 MB

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 08. INSPECT ACTUAL GROUND-TRUTH DATA
# ============================================================

from pathlib import Path
import pandas as pd

TRAIN_DIR = Path("/content/Amazon-ML-Challenge-2026/data/train")

gt_parts = sorted(TRAIN_DIR.glob("train_ground_truth.tsv.part_*"))

print("=" * 80)
print("GROUND TRUTH PARTS")
print("=" * 80)

for f in gt_parts:
    print(f"{f.name:40} {f.stat().st_size / (1024**2):.2f} MB")

print("\n" + "=" * 80)
print("FIRST 5 LINES OF EACH PART")
print("=" * 80)

for f in gt_parts:
    print(f"\n--- {f.name} ---")
    with open(f, "r", encoding="utf-8", errors="replace") as file:
        for i in range(5):
            line = file.readline()
            if not line:
                break
            print(repr(line[:500]))

print("\n" + "=" * 80)
print("PANDAS SCHEMA CHECK")
print("=" * 80)

for f in gt_parts:
    print(f"\n--- {f.name} ---")

    df = pd.read_csv(
        f,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        nrows=5
    )

    print("Columns:", df.columns.tolist())
    print("Rows sampled:", len(df))
    print(df.to_string(index=False))

================================================================================
GROUND TRUTH PARTS
================================================================================
train_ground_truth.tsv.part_aa           85.00 MB
train_ground_truth.tsv.part_ab           36.13 MB

================================================================================
FIRST 5 LINES OF EACH PART
================================================================================

--- train_ground_truth.tsv.part_aa ---
'source1_entity_id\tmatched_entity_ids\n'
'S1-965667\tS2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364\n'
'S1-55344266\tS2-249013014,S2-197070651,S3-478195123,S3-384364074\n'
'S1-343815751\tS2-790675320,S2-479876582,S3-878454467\n'
'S1-656753428\tS2-153058913,S2-24659151,S3-679606215\n'

--- train_ground_truth.tsv.part_ab ---
'-540247029\n'
'S1-868350102\tS2-991826285,S2-304774845,S3-792250844,S3-331019620,S3-446297093,S3-898127183,S3-849125640\n'
'S1-856208775\tS2-545426758,S3-376754543,S3-120322548,S3-365892577\n'
'S1-594755857\tS2-445485577,S2-482328727,S3-801769094,S3-23814742,S3-339754681,S3-996763480\n'
'S1-651810581\tS2-563675045,S2-643921143,S3-641330322,S3-880606319\n'

================================================================================
PANDAS SCHEMA CHECK
================================================================================

--- train_ground_truth.tsv.part_aa ---
Columns: ['source1_entity_id', 'matched_entity_ids']
Rows sampled: 5
source1_entity_id                                                            matched_entity_ids
        S1-965667               S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
      S1-55344266                           S2-249013014,S2-197070651,S3-478195123,S3-384364074
     S1-343815751                                        S2-790675320,S2-479876582,S3-878454467
     S1-656753428                                         S2-153058913,S2-24659151,S3-679606215
     S1-102811957 S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785

--- train_ground_truth.tsv.part_ab ---
Columns: ['-540247029']
Rows sampled: 5
                                                                                -540247029
S2-991826285,S2-304774845,S3-792250844,S3-331019620,S3-446297093,S3-898127183,S3-849125640
                                       S2-545426758,S3-376754543,S3-120322548,S3-365892577
              S2-445485577,S2-482328727,S3-801769094,S3-23814742,S3-339754681,S3-996763480
                                       S2-563675045,S2-643921143,S3-641330322,S3-880606319
                                                                   S2-735581550,S2-8591576

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 09. RECONSTRUCT FULL GROUND TRUTH
# ============================================================

from pathlib import Path
import pandas as pd

REPO = Path("/content/Amazon-ML-Challenge-2026")
TRAIN_DIR = REPO / "data" / "train"

GT_PARTS = [
    TRAIN_DIR / "train_ground_truth.tsv.part_aa",
    TRAIN_DIR / "train_ground_truth.tsv.part_ab",
]

GT_COMBINED = REPO / "outputs" / "person1_step1" / "train_ground_truth_reconstructed.tsv"

print("=" * 80)
print("RECONSTRUCTING GROUND TRUTH")
print("=" * 80)

# Concatenate the raw parts in binary mode.
# part_ab is a continuation of part_aa, so we must NOT add a header/newline.
with open(GT_COMBINED, "wb") as out:
    for part in GT_PARTS:
        print("Adding:", part.name)
        with open(part, "rb") as src:
            while True:
                chunk = src.read(8 * 1024 * 1024)
                if not chunk:
                    break
                out.write(chunk)

print("\nCreated:")
print(GT_COMBINED)
print(f"Size: {GT_COMBINED.stat().st_size / (1024**2):.2f} MB")

print("\n" + "=" * 80)
print("GROUND TRUTH SCHEMA")
print("=" * 80)

gt_sample = pd.read_csv(
    GT_COMBINED,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=5
)

print("Columns:", gt_sample.columns.tolist())
print("Sample rows:")
print(gt_sample.to_string(index=False))

print("\n" + "=" * 80)
print("GROUND TRUTH ROW COUNT")
print("=" * 80)

# Count data rows without loading the entire 121 MB file.
with open(GT_COMBINED, "rb") as f:
    total_lines = sum(1 for _ in f)

print("Total lines:", total_lines)
print("Data rows:", total_lines - 1)

================================================================================
RECONSTRUCTING GROUND TRUTH
================================================================================
Adding: train_ground_truth.tsv.part_aa
Adding: train_ground_truth.tsv.part_ab

Created:
/content/Amazon-ML-Challenge-2026/outputs/person1_step1/train_ground_truth_reconstructed.tsv
Size: 121.13 MB

================================================================================
GROUND TRUTH SCHEMA
================================================================================
Columns: ['source1_entity_id', 'matched_entity_ids']
Sample rows:
source1_entity_id                                                            matched_entity_ids
        S1-965667               S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
      S1-55344266                           S2-249013014,S2-197070651,S3-478195123,S3-384364074
     S1-343815751                                        S2-790675320,S2-479876582,S3-878454467
     S1-656753428                                         S2-153058913,S2-24659151,S3-679606215
     S1-102811957 S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785

================================================================================
GROUND TRUTH ROW COUNT
================================================================================
Total lines: 2206822
Data rows: 2206821

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 10. TRUE-MATCH BLOCKING RECALL EVALUATION
# ============================================================

!pip -q install duckdb

import duckdb
from pathlib import Path

REPO = Path("/content/Amazon-ML-Challenge-2026")

NORMALIZED_DIR = REPO / "outputs" / "person1_step1" / "normalized"
GT_FILE = REPO / "outputs" / "person1_step1" / "train_ground_truth_reconstructed.tsv"

S1 = NORMALIZED_DIR / "train_source1_normalized.tsv"
S2 = NORMALIZED_DIR / "train_source2_normalized.tsv"
S3 = NORMALIZED_DIR / "train_source3_normalized.tsv"

con = duckdb.connect()

print("=" * 80)
print("TRUE-MATCH BLOCKING RECALL EVALUATION")
print("=" * 80)

# ------------------------------------------------------------
# Load ground truth as source1 -> individual matched entity IDs
# ------------------------------------------------------------

con.execute(f"""
CREATE OR REPLACE TEMP VIEW ground_truth AS
SELECT
    source1_entity_id,
    TRIM(matched_id) AS matched_entity_id
FROM read_csv(
    '{GT_FILE}',
    delim='\\t',
    header=true,
    columns={{
        'source1_entity_id':'VARCHAR',
        'matched_entity_ids':'VARCHAR'
    }}
)
CROSS JOIN UNNEST(
    string_split(matched_entity_ids, ',')
) AS t(matched_id)
WHERE TRIM(matched_id) <> '';
""")

print("\nGround-truth pairs created.")

# ------------------------------------------------------------
# Create source views
# ------------------------------------------------------------

for name, path in [
    ("s1", S1),
    ("s2", S2),
    ("s3", S3),
]:
    con.execute(f"""
    CREATE OR REPLACE TEMP VIEW {name} AS
    SELECT
        entity_id,
        business_name,
        business_address,
        country,

        -- Blocking keys
        country || '|' || business_name AS block_name_exact,

        country || '|' ||
            substr(business_name, 1, 4) AS block_name_prefix4,

        country || '|' ||
            CASE
                WHEN strpos(business_name, ' ') > 0
                THEN substr(business_name, 1, strpos(business_name, ' ') - 1)
                ELSE business_name
            END AS block_name_token1,

        country || '|' || business_address AS block_address_exact,

        country || '|' ||
            regexp_extract(business_address, '^[^0-9]*([0-9]+)', 1)
            AS block_address_house

    FROM read_csv(
        '{path}',
        delim='\\t',
        header=true,
        columns={{
            'entity_id':'VARCHAR',
            'business_name':'VARCHAR',
            'business_address':'VARCHAR',
            'country':'VARCHAR'
        }}
    );
    """)

print("Source views created.")

# ------------------------------------------------------------
# Evaluate a blocking key for S1 -> S2 / S1 -> S3
# ------------------------------------------------------------

keys = [
    "block_name_exact",
    "block_name_prefix4",
    "block_name_token1",
    "block_address_exact",
    "block_address_house",
]

results = []

for key in keys:

    print(f"\nEvaluating: {key}")

    for target in ["s2", "s3"]:

        query = f"""
        WITH true_pairs AS (
            SELECT
                gt.source1_entity_id,
                gt.matched_entity_id,
                s1.{key} AS source1_key,
                tgt.{key} AS target_key
            FROM ground_truth gt
            JOIN s1
                ON s1.entity_id = gt.source1_entity_id
            JOIN {target} tgt
                ON tgt.entity_id = gt.matched_entity_id
            WHERE
                (
                    CASE
                        WHEN '{target}' = 's2'
                        THEN LEFT(gt.matched_entity_id, 3) = 'S2-'
                        ELSE LEFT(gt.matched_entity_id, 3) = 'S3-'
                    END
                )
        )
        SELECT
            COUNT(*) AS true_pairs,
            COUNT(*) FILTER (
                WHERE source1_key <> ''
                  AND target_key <> ''
                  AND source1_key = target_key
            ) AS captured_pairs
        FROM true_pairs;
        """

        row = con.execute(query).fetchone()

        true_pairs = row[0]
        captured = row[1]

        recall = (
            captured / true_pairs * 100
            if true_pairs
            else 0
        )

        results.append(
            (key, target.upper(), true_pairs, captured, recall)
        )

        print(
            f"  {target.upper()}: "
            f"{captured:,}/{true_pairs:,} "
            f"= {recall:.2f}%"
        )

# ------------------------------------------------------------
# Display summary
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("BLOCKING RECALL SUMMARY")
print("=" * 80)

import pandas as pd

recall_df = pd.DataFrame(
    results,
    columns=[
        "blocking_key",
        "target_source",
        "true_pairs",
        "captured_pairs",
        "recall_percent"
    ]
)

print(
    recall_df
    .sort_values(
        ["target_source", "recall_percent"],
        ascending=[True, False]
    )
    .to_string(index=False)
)

================================================================================
TRUE-MATCH BLOCKING RECALL EVALUATION
================================================================================

Ground-truth pairs created.
Source views created.

Evaluating: block_name_exact

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S2: 618,737/3,693,619 = 16.75%

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S3: 676,346/3,944,746 = 17.15%

Evaluating: block_name_prefix4

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S2: 2,805,744/3,693,619 = 75.96%

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S3: 2,944,171/3,944,746 = 74.64%

Evaluating: block_name_token1

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S2: 2,589,864/3,693,619 = 70.12%

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S3: 2,714,716/3,944,746 = 68.82%

Evaluating: block_address_exact

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S2: 395,879/3,693,619 = 10.72%

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S3: 170,383/3,944,746 = 4.32%

Evaluating: block_address_house

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S2: 2,637,456/3,693,619 = 71.41%

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  S3: 2,841,081/3,944,746 = 72.02%

================================================================================
BLOCKING RECALL SUMMARY
================================================================================
       blocking_key target_source  true_pairs  captured_pairs  recall_percent
 block_name_prefix4            S2     3693619         2805744       75.961922
block_address_house            S2     3693619         2637456       71.405741
  block_name_token1            S2     3693619         2589864       70.117248
   block_name_exact            S2     3693619          618737       16.751511
block_address_exact            S2     3693619          395879       10.717916
 block_name_prefix4            S3     3944746         2944171       74.635249
block_address_house            S3     3944746         2841081       72.021900
  block_name_token1            S3     3944746         2714716       68.818525
   block_name_exact            S3     3944746          676346       17.145489
block_address_exact            S3     3944746          170383        4.319239

In [ ]:
print("===== DATAFRAME VARIABLES IN MEMORY =====")

for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):
        print(f"{name:35s} -> {len(obj):,} rows")

===== DATAFRAME VARIABLES IN MEMORY =====
df                                  -> 5 rows
stats_df                            -> 15 rows
gt_sample                           -> 5 rows
recall_df                           -> 10 rows

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 08. COMBINED BLOCKING-KEY RECALL EVALUATION
# CHUNK-BASED VERSION
# ============================================================

from pathlib import Path
import pandas as pd
from collections import defaultdict

REPO = Path("/content/Amazon-ML-Challenge-2026")

NORMALIZED_DIR = REPO / "outputs/person1_step1/normalized"
GT_FILE = REPO / "outputs/person1_step1/train_ground_truth_reconstructed.tsv"

SOURCES = {
    "S1": NORMALIZED_DIR / "train_source1_normalized.tsv",
    "S2": NORMALIZED_DIR / "train_source2_normalized.tsv",
    "S3": NORMALIZED_DIR / "train_source3_normalized.tsv",
}

BLOCKING_KEYS = [
    "block_name_exact",
    "block_name_prefix4",
    "block_name_token1",
    "block_address_exact",
    "block_address_house",
]

print("=" * 70)
print("COMBINED BLOCKING-KEY RECALL EVALUATION")
print("=" * 70)

# ------------------------------------------------------------
# IMPORTANT:
# The blocking columns must already exist in the normalized
# data. Check them before continuing.
# ------------------------------------------------------------

required_columns = [
    "entity_id",
    "business_name",
    "business_address",
    "country"
]

sample = pd.read_csv(
    SOURCES["S1"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=5
)

print("Available columns:")
print(sample.columns.tolist())

missing = [c for c in required_columns if c not in sample.columns]

if missing:
    raise ValueError(
        f"Missing required columns: {missing}"
    )

print("\nNormalized files confirmed.")
for source, path in SOURCES.items():
    print(f"{source}: {path.name}")

print("\nGround truth:")
print(GT_FILE)

======================================================================
COMBINED BLOCKING-KEY RECALL EVALUATION
======================================================================
Available columns:
['entity_id', 'business_name', 'business_address', 'country']

Normalized files confirmed.
S1: train_source1_normalized.tsv
S2: train_source2_normalized.tsv
S3: train_source3_normalized.tsv

Ground truth:
/content/Amazon-ML-Challenge-2026/outputs/person1_step1/train_ground_truth_reconstructed.tsv

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 09. RECREATE BLOCKING KEYS FOR GROUND-TRUTH ENTITIES
# ============================================================

import re
import pandas as pd

print("=" * 70)
print("RECREATING BLOCKING KEYS FOR GROUND-TRUTH ENTITIES")
print("=" * 70)

# ------------------------------------------------------------
# Blocking-key functions
# ------------------------------------------------------------

def clean_block_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip().lower()


def make_block_name_exact(x):
    return clean_block_text(x)


def make_block_name_prefix4(x):
    x = clean_block_text(x)
    return x[:4] if x else ""


def make_block_name_token1(x):
    x = clean_block_text(x)
    if not x:
        return ""
    return x.split()[0]


def make_block_address_exact(x):
    return clean_block_text(x)


def make_block_address_house(x):
    x = clean_block_text(x)

    if not x:
        return ""

    # First numeric token = house/building number
    match = re.search(r"\d+", x)

    if match:
        return match.group(0)

    return ""


# ------------------------------------------------------------
# Read ground truth
# ------------------------------------------------------------

gt = pd.read_csv(
    GT_FILE,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print(f"Ground-truth rows: {len(gt):,}")

# ------------------------------------------------------------
# Collect all entity IDs required for evaluation
# ------------------------------------------------------------

needed_ids = {
    "S1": set(gt["source1_entity_id"].astype(str))
}

for source in ["S2", "S3"]:

    ids = set()

    for value in gt["matched_entity_ids"]:

        for entity_id in str(value).split(","):

            entity_id = entity_id.strip()

            if entity_id.startswith(source):
                ids.add(entity_id)

    needed_ids[source] = ids

print("\nRequired entity IDs:")
for source, ids in needed_ids.items():
    print(f"{source}: {len(ids):,}")

# ------------------------------------------------------------
# Read only required rows from each normalized dataset
# ------------------------------------------------------------

needed_rows = {}

for source, path in SOURCES.items():

    print(f"\nReading {source}...")

    chunks = []

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=250_000
    ):

        mask = chunk["entity_id"].isin(needed_ids[source])

        if mask.any():
            chunks.append(chunk.loc[mask].copy())

    if chunks:
        df_source = pd.concat(chunks, ignore_index=True)
    else:
        df_source = pd.DataFrame(
            columns=[
                "entity_id",
                "business_name",
                "business_address",
                "country"
            ]
        )

    # --------------------------------------------------------
    # Create blocking keys
    # --------------------------------------------------------

    df_source["block_name_exact"] = (
        df_source["business_name"]
        .map(make_block_name_exact)
    )

    df_source["block_name_prefix4"] = (
        df_source["business_name"]
        .map(make_block_name_prefix4)
    )

    df_source["block_name_token1"] = (
        df_source["business_name"]
        .map(make_block_name_token1)
    )

    df_source["block_address_exact"] = (
        df_source["business_address"]
        .map(make_block_address_exact)
    )

    df_source["block_address_house"] = (
        df_source["business_address"]
        .map(make_block_address_house)
    )

    needed_rows[source] = df_source

    print(
        f"{source}: {len(df_source):,} required rows loaded"
    )

print("\n" + "=" * 70)
print("BLOCKING KEYS RECREATED SUCCESSFULLY")
print("=" * 70)

for source, df_source in needed_rows.items():

    print(
        f"\n{source}: {len(df_source):,} rows"
    )

    print(
        df_source[
            [
                "entity_id",
                "block_name_exact",
                "block_name_prefix4",
                "block_name_token1",
                "block_address_exact",
                "block_address_house"
            ]
        ].head(3).to_string(index=False)
    )

======================================================================
RECREATING BLOCKING KEYS FOR GROUND-TRUTH ENTITIES
======================================================================
Ground-truth rows: 2,206,821

Required entity IDs:
S1: 2,206,821
S2: 3,693,619
S3: 3,944,746

Reading S1...
S1: 2,206,821 required rows loaded

Reading S2...
S2: 3,693,619 required rows loaded

Reading S3...
S3: 3,944,746 required rows loaded

======================================================================
BLOCKING KEYS RECREATED SUCCESSFULLY
======================================================================

S1: 2,206,821 rows
   entity_id    block_name_exact block_name_prefix4 block_name_token1                    block_address_exact block_address_house
S1-925783039 orelee's barbershop               orel          orelee's 1795 westchester drive, high point, nc                1795
S1-773889195         prime money               prim             prime        17560 ellis road, tahlequah, ok               17560
S1-377745466       b+ retail inc               b+ r                b+    1712 montebello avenue, phoenix, az                1712

S2: 3,693,619 rows
   entity_id                        block_name_exact block_name_prefix4 block_name_token1                                      block_address_exact block_address_house
 S2-49942811            delta tetlecommunication inc               delt             delta                          914 pierpont ave, cleveland, oh                 914
S2-138046867                          lee and lawson               lee                lee                  1702 pine avenue, city of menomonie, wi                1702
S2-508602797 foundation excel agency private limited               foun        foundation hn 753 e-1, bharat nagar, 104/1/1 erandwane, maharashtra                 753

S3: 3,944,746 rows
   entity_id                            block_name_exact block_name_prefix4  block_name_token1             block_address_exact block_address_house
S3-202863386                          wilfordhancock.com               wilf wilfordhancock.com     mack rd, haltom city, texas
S3-859268022 international south consultants private ltd               inte      international
 S3-22467283                 llc moncada léarning center               llc                 llc 5780 fawn ct, fort worth, texas                5780

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 10. COMBINED BLOCKING RECALL EVALUATION
# ============================================================

import pandas as pd

print("=" * 70)
print("COMBINED BLOCKING-KEY RECALL EVALUATION")
print("=" * 70)

# Blocking keys to test
BLOCKING_KEYS = [
    "block_name_exact",
    "block_name_prefix4",
    "block_name_token1",
    "block_address_exact",
    "block_address_house",
]

# ------------------------------------------------------------
# Build fast entity_id -> blocking-key lookup
# ------------------------------------------------------------

print("\nBuilding lookup tables...")

lookup = {}

for source, df in needed_rows.items():

    lookup[source] = (
        df.set_index("entity_id")[BLOCKING_KEYS]
    )

    print(
        f"{source}: {len(lookup[source]):,} entities indexed"
    )

# ------------------------------------------------------------
# Evaluate each ground-truth relationship
# ------------------------------------------------------------

results = []

for idx, row in gt.iterrows():

    if idx % 250_000 == 0:
        print(f"Processed {idx:,} / {len(gt):,}")

    s1_id = str(row["source1_entity_id"])

    if s1_id not in lookup["S1"].index:
        continue

    s1_keys = lookup["S1"].loc[s1_id]

    # matched S2/S3 IDs
    matched_ids = [
        x.strip()
        for x in str(row["matched_entity_ids"]).split(",")
        if x.strip()
    ]

    for target_id in matched_ids:

        if target_id.startswith("S2"):
            source = "S2"
        elif target_id.startswith("S3"):
            source = "S3"
        else:
            continue

        if target_id not in lookup[source].index:
            continue

        target_keys = lookup[source].loc[target_id]

        result = {
            "source1_entity_id": s1_id,
            "target_entity_id": target_id,
            "target_source": source,
        }

        # Individual key matches
        for key in BLOCKING_KEYS:
            result[key] = (
                bool(s1_keys[key])
                and bool(target_keys[key])
                and s1_keys[key] == target_keys[key]
            )

        # Combined OR blocking
        result["combined_match"] = any(
            result[key] for key in BLOCKING_KEYS
        )

        results.append(result)

# ------------------------------------------------------------
# Results dataframe
# ------------------------------------------------------------

recall_eval = pd.DataFrame(results)

print("\n" + "=" * 70)
print("COMBINED BLOCKING RECALL RESULTS")
print("=" * 70)

print(
    f"\nTrue-match pairs evaluated: "
    f"{len(recall_eval):,}"
)

for key in BLOCKING_KEYS:

    captured = recall_eval[key].sum()

    recall = (
        captured / len(recall_eval) * 100
        if len(recall_eval)
        else 0
    )

    print(
        f"{key:25s}: "
        f"{captured:,} / {len(recall_eval):,} "
        f"= {recall:.2f}%"
    )

captured = recall_eval["combined_match"].sum()

combined_recall = (
    captured / len(recall_eval) * 100
    if len(recall_eval)
    else 0
)

print("-" * 70)

print(
    f"{'COMBINED OR':25s}: "
    f"{captured:,} / {len(recall_eval):,} "
    f"= {combined_recall:.2f}%"
)

print("=" * 70)

======================================================================
COMBINED BLOCKING-KEY RECALL EVALUATION
======================================================================

Building lookup tables...

NameError: name 'needed_rows' is not defined

In [ ]:
import os

print("=== RUNTIME CHECK ===")
print("Repo exists:", os.path.exists("/content/Amazon-ML-Challenge-2026"))
print("Current directory:", os.getcwd())

if os.path.exists("/content/Amazon-ML-Challenge-2026"):
    print("Repo contents:")
    print(os.listdir("/content/Amazon-ML-Challenge-2026")[:20])
else:
    print("Repo is NOT present — runtime reset removed it.")

=== RUNTIME CHECK ===
Repo exists: True
Current directory: /content
Repo contents:
['outputs', 'data', '.gitignore', 'reconstruct_data.sh', '.git', 'notebooks', 'README.md', '.gitattributes', 'src']

In [ ]:
# ============================================================
# STEP 4 — BLOCKING
# 09. MEMORY-SAFE RELOAD FOR COMBINED RECALL
# ============================================================

from pathlib import Path
import pandas as pd
import gc

REPO = Path("/content/Amazon-ML-Challenge-2026")

NORMALIZED_DIR = REPO / "outputs/person1_step1/normalized"
GT_FILE = REPO / "outputs/person1_step1/train_ground_truth_reconstructed.tsv"

SOURCE_FILES = {
    "S1": NORMALIZED_DIR / "train_source1_normalized.tsv",
    "S2": NORMALIZED_DIR / "train_source2_normalized.tsv",
    "S3": NORMALIZED_DIR / "train_source3_normalized.tsv",
}

BLOCKING_KEYS = [
    "block_name_exact",
    "block_name_prefix4",
    "block_name_token1",
    "block_address_exact",
    "block_address_house",
]

print("=" * 70)
print("MEMORY-SAFE BLOCKING RELOAD")
print("=" * 70)

# ------------------------------------------------------------
# Load ONLY ground truth
# ------------------------------------------------------------

gt = pd.read_csv(
    GT_FILE,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print(f"\nGround-truth rows: {len(gt):,}")
print("Ground-truth columns:", gt.columns.tolist())

# ------------------------------------------------------------
# Check normalized files
# ------------------------------------------------------------

print("\nNormalized source files:")

for source, path in SOURCE_FILES.items():
    print(
        f"{source}: {path.name} | "
        f"{path.stat().st_size / (1024**2):.2f} MB"
    )

print("\nReady for memory-safe evaluation.")

======================================================================
MEMORY-SAFE BLOCKING RELOAD
======================================================================

Ground-truth rows: 2,206,821
Ground-truth columns: ['source1_entity_id', 'matched_entity_ids']

Normalized source files:
S1: train_source1_normalized.tsv | 200.31 MB
S2: train_source2_normalized.tsv | 451.53 MB
S3: train_source3_normalized.tsv | 470.15 MB

Ready for memory-safe evaluation.

In [ ]:
# ============================================================
# STEP 4 — MEMORY-SAFE COMBINED BLOCKING RECALL
# Recreate blocking keys from normalized data
# ============================================================

import pandas as pd
import re
from collections import defaultdict

print("=" * 70)
print("MEMORY-SAFE COMBINED BLOCKING RECALL")
print("=" * 70)

# ------------------------------------------------------------
# Blocking-key functions
# ------------------------------------------------------------

def name_exact(x):
    return str(x).strip()

def name_prefix4(x):
    x = str(x).strip()
    return x[:4] if x else ""

def name_token1(x):
    x = str(x).strip()
    return x.split()[0] if x else ""

def address_exact(x):
    return str(x).strip()

def address_house(x):
    x = str(x).strip()
    m = re.search(r'\b\d+[A-Za-z]?\b', x)
    return m.group(0) if m else ""


# ------------------------------------------------------------
# Create ground-truth pair lists
# ------------------------------------------------------------

gt_pairs = []

for row in gt.itertuples(index=False):
    s1_id = row.source1_entity_id
    matched = str(row.matched_entity_ids).split(",")

    for target_id in matched:
        target_id = target_id.strip()

        if target_id.startswith("S2-"):
            gt_pairs.append((s1_id, target_id, "S2"))

        elif target_id.startswith("S3-"):
            gt_pairs.append((s1_id, target_id, "S3"))

print(f"Total ground-truth pairs: {len(gt_pairs):,}")

# ------------------------------------------------------------
# Ground-truth ID sets
# ------------------------------------------------------------

s1_ids = set(x[0] for x in gt_pairs)
s2_ids = set(x[1] for x in gt_pairs if x[2] == "S2")
s3_ids = set(x[1] for x in gt_pairs if x[2] == "S3")

print(f"S1 IDs required: {len(s1_ids):,}")
print(f"S2 IDs required: {len(s2_ids):,}")
print(f"S3 IDs required: {len(s3_ids):,}")


# ------------------------------------------------------------
# Read ONLY required rows from a source file
# ------------------------------------------------------------

def load_required_rows(path, required_ids):

    result = {}

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=200_000
    ):

        mask = chunk["entity_id"].isin(required_ids)

        if mask.any():

            selected = chunk.loc[
                mask,
                [
                    "entity_id",
                    "business_name",
                    "business_address"
                ]
            ]

            for row in selected.itertuples(index=False):

                entity_id = row.entity_id
                name = row.business_name
                address = row.business_address

                result[entity_id] = {
                    "block_name_exact": name_exact(name),
                    "block_name_prefix4": name_prefix4(name),
                    "block_name_token1": name_token1(name),
                    "block_address_exact": address_exact(address),
                    "block_address_house": address_house(address),
                }

        del chunk

    return result


# ------------------------------------------------------------
# Load only GT-required records
# ------------------------------------------------------------

print("\nLoading S1 required rows...")
s1_lookup = load_required_rows(SOURCE_FILES["S1"], s1_ids)
print(f"S1 loaded: {len(s1_lookup):,}")

print("\nLoading S2 required rows...")
s2_lookup = load_required_rows(SOURCE_FILES["S2"], s2_ids)
print(f"S2 loaded: {len(s2_lookup):,}")

print("\nLoading S3 required rows...")
s3_lookup = load_required_rows(SOURCE_FILES["S3"], s3_ids)
print(f"S3 loaded: {len(s3_lookup):,}")


# ------------------------------------------------------------
# Evaluate blocking recall
# ------------------------------------------------------------

BLOCK_KEYS = [
    "block_name_exact",
    "block_name_prefix4",
    "block_name_token1",
    "block_address_exact",
    "block_address_house",
]

results = []

for s1_id, target_id, target_source in gt_pairs:

    if s1_id not in s1_lookup:
        continue

    target_lookup = s2_lookup if target_source == "S2" else s3_lookup

    if target_id not in target_lookup:
        continue

    s1_keys = s1_lookup[s1_id]
    target_keys = target_lookup[target_id]

    row = {
        "source1_entity_id": s1_id,
        "target_entity_id": target_id,
        "target_source": target_source,
    }

    captured_any = False

    for key in BLOCK_KEYS:

        captured = (
            bool(s1_keys[key])
            and bool(target_keys[key])
            and s1_keys[key] == target_keys[key]
        )

        row[key] = captured

        if captured:
            captured_any = True

    row["combined"] = captured_any

    results.append(row)


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

recall_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("FINAL BLOCKING RECALL")
print("=" * 70)

for key in BLOCK_KEYS + ["combined"]:

    recall = recall_df[key].mean() * 100

    print(
        f"{key:25s}: "
        f"{recall_df[key].sum():,} / "
        f"{len(recall_df):,} = "
        f"{recall:.2f}%"
    )

print("\n" + "=" * 70)
print("BLOCKING EVALUATION INPUT READY")
print("=" * 70)

======================================================================
MEMORY-SAFE COMBINED BLOCKING RECALL
======================================================================
Total ground-truth pairs: 7,638,365
S1 IDs required: 2,083,574
S2 IDs required: 3,693,619
S3 IDs required: 3,944,746

Loading S1 required rows...
S1 loaded: 2,083,574

Loading S2 required rows...
S2 loaded: 3,693,619

Loading S3 required rows...
S3 loaded: 3,944,746

In [ ]:
# ============================================================
# STEP 5 — FINAL COMBINED BLOCKING RECALL EVALUATION
# ============================================================

import os
import duckdb
import pandas as pd

BASE = "/content/Amazon-ML-Challenge-2026"
OUT = os.path.join(BASE, "outputs", "person1_step1")

DB_PATH = os.path.join(OUT, "blocking_eval.duckdb")
TMP_DIR = os.path.join(OUT, "duckdb_tmp")

os.makedirs(TMP_DIR, exist_ok=True)

db = duckdb.connect(DB_PATH)

db.execute("SET memory_limit='4GB'")
db.execute("SET threads=2")
db.execute("SET preserve_insertion_order=false")
db.execute(f"SET temp_directory='{TMP_DIR}'")

print("=" * 70)
print("COMBINED BLOCKING RECALL EVALUATION")
print("=" * 70)
print("Memory limit :", "4 GB")
print("Threads      :", 2)
print("Temp disk    :", TMP_DIR)


# ------------------------------------------------------------
# FILES
# ------------------------------------------------------------

GT_FILE = os.path.join(
    OUT,
    "train_ground_truth_reconstructed.tsv"
)

S1_FILE = os.path.join(
    OUT,
    "normalized",
    "train_source1_normalized.tsv"
)

S2_FILE = os.path.join(
    OUT,
    "normalized",
    "train_source2_normalized.tsv"
)

S3_FILE = os.path.join(
    OUT,
    "normalized",
    "train_source3_normalized.tsv"
)


# ------------------------------------------------------------
# EVALUATE ONE TARGET SOURCE
# ------------------------------------------------------------

def evaluate_target(target_name, target_file):

    print("\n" + "=" * 70)
    print(f"EVALUATING {target_name}")
    print("=" * 70)

    query = f"""
    WITH

    /* --------------------------------------------------------
       1. Expand ground truth into individual S1 -> target pairs
       -------------------------------------------------------- */

    gt_pairs AS
    (
        SELECT
            source1_entity_id,
            TRIM(u.matched_id) AS matched_entity_id

        FROM
        (
            SELECT
                source1_entity_id,
                matched_entity_ids
            FROM read_csv(
                '{GT_FILE}',
                delim='\\t',
                header=true,
                all_varchar=true
            )
        ) g

        CROSS JOIN UNNEST(
            string_split(g.matched_entity_ids, ',')
        ) AS u(matched_id)

        WHERE TRIM(u.matched_id) <> ''
    ),


    /* --------------------------------------------------------
       2. Join S1 and target records
       -------------------------------------------------------- */

    pairs AS
    (
        SELECT

            g.source1_entity_id,
            g.matched_entity_id,

            TRIM(s1.business_name)
                AS s1_name,

            TRIM(s1.business_address)
                AS s1_address,

            TRIM(t.business_name)
                AS target_name,

            TRIM(t.business_address)
                AS target_address

        FROM gt_pairs g

        INNER JOIN read_csv(
            '{S1_FILE}',
            delim='\\t',
            header=true,
            all_varchar=true
        ) s1

            ON s1.entity_id = g.source1_entity_id

        INNER JOIN read_csv(
            '{target_file}',
            delim='\\t',
            header=true,
            all_varchar=true
        ) t

            ON t.entity_id = g.matched_entity_id
    ),


    /* --------------------------------------------------------
       3. Calculate all blocking-key matches
       -------------------------------------------------------- */

    checks AS
    (
        SELECT

            source1_entity_id,
            matched_entity_id,

            /* Exact name */
            (
                s1_name = target_name
                AND s1_name <> ''
            ) AS name_exact,


            /* First 4 characters of name */
            (
                LEFT(s1_name, 4)
                =
                LEFT(target_name, 4)

                AND s1_name <> ''
                AND target_name <> ''
            ) AS name_prefix4,


            /* First whitespace-separated name token */
            (
                split_part(s1_name, ' ', 1)
                =
                split_part(target_name, ' ', 1)

                AND s1_name <> ''
                AND target_name <> ''
            ) AS name_token1,


            /* Exact address */
            (
                s1_address = target_address
                AND s1_address <> ''
            ) AS address_exact,


            /* House number */
            (
                regexp_extract(
                    s1_address,
                    '[0-9]+[A-Za-z]?',
                    0
                )
                =
                regexp_extract(
                    target_address,
                    '[0-9]+[A-Za-z]?',
                    0
                )

                AND regexp_extract(
                    s1_address,
                    '[0-9]+[A-Za-z]?',
                    0
                ) <> ''
            ) AS address_house

        FROM pairs
    )


    /* --------------------------------------------------------
       4. Aggregate recall
       -------------------------------------------------------- */

    SELECT

        COUNT(*) AS total_pairs,

        SUM(
            CASE
                WHEN name_exact THEN 1
                ELSE 0
            END
        ) AS name_exact_hits,

        SUM(
            CASE
                WHEN name_prefix4 THEN 1
                ELSE 0
            END
        ) AS name_prefix4_hits,

        SUM(
            CASE
                WHEN name_token1 THEN 1
                ELSE 0
            END
        ) AS name_token1_hits,

        SUM(
            CASE
                WHEN address_exact THEN 1
                ELSE 0
            END
        ) AS address_exact_hits,

        SUM(
            CASE
                WHEN address_house THEN 1
                ELSE 0
            END
        ) AS address_house_hits,

        SUM(
            CASE
                WHEN
                    name_exact
                    OR name_prefix4
                    OR name_token1
                    OR address_exact
                    OR address_house
                THEN 1
                ELSE 0
            END
        ) AS combined_hits

    FROM checks
    """

    print("Running DuckDB evaluation...")
    print("Target:", target_name)

    result = db.execute(query).fetchone()

    total = int(result[0])

    metrics = {
        "target": target_name,
        "total_pairs": total,
        "name_exact_hits": int(result[1]),
        "name_prefix4_hits": int(result[2]),
        "name_token1_hits": int(result[3]),
        "address_exact_hits": int(result[4]),
        "address_house_hits": int(result[5]),
        "combined_hits": int(result[6]),
    }

    print("\nCOUNTS")
    print("-" * 70)

    for key, value in metrics.items():
        if isinstance(value, int):
            print(f"{key:25s}: {value:,}")
        else:
            print(f"{key:25s}: {value}")

    print("\nRECALL")
    print("-" * 70)

    for key in [
        "name_exact_hits",
        "name_prefix4_hits",
        "name_token1_hits",
        "address_exact_hits",
        "address_house_hits",
        "combined_hits"
    ]:
        recall = metrics[key] / total * 100
        print(f"{key:25s}: {recall:.2f}%")

    return metrics


# ------------------------------------------------------------
# RUN S2
# ------------------------------------------------------------

s2_result = evaluate_target(
    "S2",
    S2_FILE
)


# ------------------------------------------------------------
# RUN S3
# ------------------------------------------------------------

s3_result = evaluate_target(
    "S3",
    S3_FILE
)


# ------------------------------------------------------------
# BUILD FINAL TABLE
# ------------------------------------------------------------

results = pd.DataFrame([
    s2_result,
    s3_result
])

for key in [
    "name_exact",
    "name_prefix4",
    "name_token1",
    "address_exact",
    "address_house",
    "combined"
]:

    results[f"{key}_recall"] = (
        results[f"{key}_hits"]
        / results["total_pairs"]
        * 100
    )


# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

RESULT_FILE = os.path.join(
    OUT,
    "blocking_recall_evaluation.tsv"
)

results.to_csv(
    RESULT_FILE,
    sep="\t",
    index=False
)


print("\n" + "=" * 70)
print("FINAL RESULTS")
print("=" * 70)

display(results)

print("\nSaved:")
print(RESULT_FILE)

======================================================================
COMBINED BLOCKING RECALL EVALUATION
======================================================================
Memory limit : 4 GB
Threads      : 2
Temp disk    : /content/Amazon-ML-Challenge-2026/outputs/person1_step1/duckdb_tmp

======================================================================
EVALUATING S2
======================================================================
Running DuckDB evaluation...
Target: S2

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

COUNTS
----------------------------------------------------------------------
target                   : S2
total_pairs              : 3,693,619
name_exact_hits          : 618,737
name_prefix4_hits        : 2,805,744
name_token1_hits         : 2,589,864
address_exact_hits       : 395,879
address_house_hits       : 2,494,283
combined_hits            : 3,415,531

RECALL
----------------------------------------------------------------------
name_exact_hits          : 16.75%
name_prefix4_hits        : 75.96%
name_token1_hits         : 70.12%
address_exact_hits       : 10.72%
address_house_hits       : 67.53%
combined_hits            : 92.47%

======================================================================
EVALUATING S3
======================================================================
Running DuckDB evaluation...
Target: S3

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

COUNTS
----------------------------------------------------------------------
target                   : S3
total_pairs              : 3,944,746
name_exact_hits          : 676,346
name_prefix4_hits        : 2,944,171
name_token1_hits         : 2,714,716
address_exact_hits       : 170,383
address_house_hits       : 2,689,727
combined_hits            : 3,678,626

RECALL
----------------------------------------------------------------------
name_exact_hits          : 17.15%
name_prefix4_hits        : 74.64%
name_token1_hits         : 68.82%
address_exact_hits       : 4.32%
address_house_hits       : 68.19%
combined_hits            : 93.25%

======================================================================
FINAL RESULTS
======================================================================

,target,total_pairs,name_exact_hits,name_prefix4_hits,name_token1_hits,address_exact_hits,address_house_hits,combined_hits,name_exact_recall,name_prefix4_recall,name_token1_recall,address_exact_recall,address_house_recall,combined_recall
0,S2,3693619,618737,2805744,2589864,395879,2494283,3415531,16.751511,75.961922,70.117248,10.717916,67.529515,92.471124
1,S3,3944746,676346,2944171,2714716,170383,2689727,3678626,17.145489,74.635249,68.818525,4.319239,68.185049,93.253812

Saved:
/content/Amazon-ML-Challenge-2026/outputs/person1_step1/blocking_recall_evaluation.tsv

In [ ]:
%cd /content/Amazon-ML-Challenge-2026

# Configure local git identity for this session
!git config --local user.email "krishna.gera@example.com"
!git config --local user.name "krishna-gera"

# Stage and commit
!git add .
!git commit -m "blocking stage"

# Safely authenticate and push using Colab Secrets
from google.colab import userdata
TOKEN = userdata.get('GH_TOKEN')
USERNAME = "krishna-gera"
REPO_OWNER = "Ayushxsingh100"
REPO_NAME = "Amazon-ML-Challenge-2026"
BRANCH = "main"

!git push https://{USERNAME}:{TOKEN}@github.com/{REPO_OWNER}/{REPO_NAME}.git {BRANCH}

/content/Amazon-ML-Challenge-2026
[main c87e404] blocking stage
 3 files changed, 6 insertions(+)
 create mode 100644 outputs/person1_step1/blocking_eval.duckdb
 create mode 100644 outputs/person1_step1/blocking_recall_evaluation.tsv
 create mode 100644 outputs/person1_step1/train_ground_truth_reconstructed.tsv
Uploading LFS objects: 100% (2/2), 127 MB | 25 MB/s, done.
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 848 bytes | 848.00 KiB/s, done.
Total 7 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/Ayushxsingh100/Amazon-ML-Challenge-2026.git
   24f6a97..c87e404  main -> main

In [1]:
%cd /content

!git clone https://github.com/Ayushxsingh100/Amazon-ML-Challenge-2026.git

/content
Cloning into 'Amazon-ML-Challenge-2026'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 133 (delta 24), reused 112 (delta 22), pack-reused 15 (from 1)
Receiving objects: 100% (133/133), 90.50 KiB | 1.37 MiB/s, done.
Resolving deltas: 100% (24/24), done.

In [2]:
%cd /content/Amazon-ML-Challenge-2026

/content/Amazon-ML-Challenge-2026

In [4]:
!ls -lah
!find outputs/person1_step1 -maxdepth 2 -type f | head -30

total 44K
drwxr-xr-x 7 root root 4.0K Sep 25 06:31 .
drwxr-xr-x 1 root root 4.0K Sep 25 06:31 ..
drwxr-xr-x 4 root root 4.0K Sep 25 06:31 data
drwxr-xr-x 8 root root 4.0K Sep 25 06:31 .git
-rw-r--r-- 1 root root   91 Sep 25 06:31 .gitattributes
-rw-r--r-- 1 root root  374 Sep 25 06:31 .gitignore
drwxr-xr-x 2 root root 4.0K Sep 25 06:31 notebooks
drwxr-xr-x 3 root root 4.0K Sep 25 06:31 outputs
-rw-r--r-- 1 root root 2.8K Sep 25 06:31 README.md
-rwxr-xr-x 1 root root  980 Sep 25 06:31 reconstruct_data.sh
drwxr-xr-x 2 root root 4.0K Sep 25 06:31 src
outputs/person1_step1/blocking_eval.duckdb
outputs/person1_step1/train_source3_missing_values.tsv
outputs/person1_step1/s1_full_match_count_distribution.tsv
outputs/person1_step1/train_source1_blank_values.tsv
outputs/person1_step1/string_length_statistics.tsv
outputs/person1_step1/s1_match_source_composition.tsv
outputs/person1_step1/ground_truth_entity_match_distribution.tsv
outputs/person1_step1/train_source1_missing_values.tsv
outputs/person1_step1/train_ground_truth_missing_values.tsv
outputs/person1_step1/train_source2_blank_values.tsv
outputs/person1_step1/train_source2_country_distribution.tsv
outputs/person1_step1/id_prefix_summary.tsv
outputs/person1_step1/test_id_prefix_summary.tsv
outputs/person1_step1/train_dataset_row_counts.tsv
outputs/person1_step1/train_ground_truth_reconstructed.tsv
outputs/person1_step1/train_id_prefix_summary.tsv
outputs/person1_step1/test_dataset_row_counts.tsv
outputs/person1_step1/train_ground_truth_blank_values.tsv
outputs/person1_step1/duplicate_id_summary.tsv
outputs/person1_step1/train_source3_country_distribution.tsv
outputs/person1_step1/dataset_row_counts.tsv
outputs/person1_step1/train_source2_missing_values.tsv
outputs/person1_step1/normalized/test_source2_normalized.tsv
outputs/person1_step1/normalized/test_source1_normalized.tsv
outputs/person1_step1/normalized/train_source3_normalized.tsv
outputs/person1_step1/normalized/train_source2_normalized.tsv
outputs/person1_step1/normalized/train_source1_normalized.tsv
outputs/person1_step1/normalized/test_source3_normalized.tsv
outputs/person1_step1/train_source1_country_distribution.tsv
outputs/person1_step1/train_source3_blank_values.tsv

In [3]:
!apt-get update -qq
!apt-get install -y git-lfs -qq

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package git-lfs.
(Reading database ... 122809 files and directories currently installed.)
Preparing to unpack .../git-lfs_3.4.1-1ubuntu0.4_amd64.deb ...
Unpacking git-lfs (3.4.1-1ubuntu0.4) ...
Setting up git-lfs (3.4.1-1ubuntu0.4) ...
Processing triggers for man-db (2.12.0-4build2) ...

In [4]:
%cd /content/Amazon-ML-Challenge-2026

!git lfs install

/content/Amazon-ML-Challenge-2026
Updated Git hooks.
Git LFS initialized.

In [ ]:
!git lfs pull

In [ ]:
!git status

In [ ]:
!ls -lh outputs/person1_step1/normalized/
!ls -lh outputs/person1_step1/*blocking* outputs/person1_step1/*strategy*

In [ ]:
!head -3 outputs/person1_step1/blocking_recall_evaluation.tsv

In [11]:
import os

BASE = "/content/Amazon-ML-Challenge-2026"
OUT = f"{BASE}/outputs/person1_step1"

files = [
    "train_ground_truth_reconstructed.tsv",
    "blocking_recall_evaluation.tsv",
    "compound_blocking_recall_evaluation.tsv",
    "practical_blocking_combinations.tsv",
    "final_blocking_strategy_search.tsv",
    "test_candidate_volume_estimate.tsv",
]

for f in files:
    path = os.path.join(OUT, f)
    if os.path.exists(path):
        print(f"✓ {f:45s} {os.path.getsize(path)/1024/1024:.1f} MB")
    else:
        print(f"✗ MISSING: {f}")

✓ train_ground_truth_reconstructed.tsv          121.1 MB
✓ blocking_recall_evaluation.tsv                0.0 MB
✗ MISSING: compound_blocking_recall_evaluation.tsv
✗ MISSING: practical_blocking_combinations.tsv
✗ MISSING: final_blocking_strategy_search.tsv
✗ MISSING: test_candidate_volume_estimate.tsv

In [12]:
%cd /content/Amazon-ML-Challenge-2026

!git lfs ls-files
!echo "----"
!ls -lh outputs/person1_step1/blocking_recall_evaluation.tsv
!echo "----"
!head -3 outputs/person1_step1/blocking_recall_evaluation.tsv

/content/Amazon-ML-Challenge-2026
a443d81d9f * data/test/test_source1.tsv.part_aa
27312db129 * data/test/test_source1.tsv.part_ab
8afb463a6c * data/test/test_source2.tsv.part_aa
dab2f26cd4 * data/test/test_source2.tsv.part_ab
d704ee1766 * data/test/test_source2.tsv.part_ac
0f40e1f360 * data/test/test_source2.tsv.part_ad
1a41948f8a * data/test/test_source2.tsv.part_ae
5ddb5aa57a * data/test/test_source2.tsv.part_af
e07534e3a5 * data/test/test_source3.tsv.part_aa
ac13527c7f * data/test/test_source3.tsv.part_ab
4959357bed * data/test/test_source3.tsv.part_ac
59f56e2973 * data/test/test_source3.tsv.part_ad
0b668bc604 * data/test/test_source3.tsv.part_ae
f2105c2317 * data/test/test_source3.tsv.part_af
6a3b035b82 * data/train/train_ground_truth.tsv.part_aa
fe41b518ba * data/train/train_ground_truth.tsv.part_ab
ebbeb920bf * data/train/train_source1.tsv.part_aa
dce51ab2ce * data/train/train_source1.tsv.part_ab
e7498ef08d * data/train/train_source1.tsv.part_ac
79bca3f873 * data/train/train_source2.tsv.part_aa
0bcc1ca7a7 * data/train/train_source2.tsv.part_ab
aad935b912 * data/train/train_source2.tsv.part_ac
31093f21bc * data/train/train_source2.tsv.part_ad
7e6c148ec6 * data/train/train_source2.tsv.part_ae
5ba58464b0 * data/train/train_source2.tsv.part_af
06af75d52e * data/train/train_source3.tsv.part_aa
e2137f082b * data/train/train_source3.tsv.part_ab
863c7efad8 * data/train/train_source3.tsv.part_ac
9f9ff2bf23 * data/train/train_source3.tsv.part_ad
03e77d7175 * data/train/train_source3.tsv.part_ae
fc93a53d5e * data/train/train_source3.tsv.part_af
c3edd7a29b * outputs/person1_step1/blocking_recall_evaluation.tsv
512f1092bf * outputs/person1_step1/column_information.tsv
bfd735470f * outputs/person1_step1/dataset_row_counts.tsv
2960552a19 * outputs/person1_step1/duplicate_id_summary.tsv
b22e482625 * outputs/person1_step1/ground_truth_entity_match_distribution.tsv
8af0856f81 * outputs/person1_step1/id_prefix_summary.tsv
f6ce879034 * outputs/person1_step1/normalized/test_source1_normalized.tsv
5bc01f5e54 * outputs/person1_step1/normalized/test_source2_normalized.tsv
58ef93ced2 * outputs/person1_step1/normalized/test_source3_normalized.tsv
05d53a5d74 * outputs/person1_step1/normalized/train_source1_normalized.tsv
a637b672ee * outputs/person1_step1/normalized/train_source2_normalized.tsv
13fbd7561f * outputs/person1_step1/normalized/train_source3_normalized.tsv
53a42670d8 * outputs/person1_step1/s1_full_match_count_distribution.tsv
014203079d * outputs/person1_step1/s1_match_source_composition.tsv
934d5c8867 * outputs/person1_step1/string_length_statistics.tsv
cb0c2bb737 * outputs/person1_step1/test_dataset_row_counts.tsv
d33f5674c7 * outputs/person1_step1/test_id_prefix_summary.tsv
bfd735470f * outputs/person1_step1/train_dataset_row_counts.tsv
bbd7f6c3f2 * outputs/person1_step1/train_ground_truth_blank_values.tsv
c19d8897af * outputs/person1_step1/train_ground_truth_missing_values.tsv
70bc1d8a16 * outputs/person1_step1/train_ground_truth_reconstructed.tsv
8af0856f81 * outputs/person1_step1/train_id_prefix_summary.tsv
4c860a9cd2 * outputs/person1_step1/train_source1_blank_values.tsv
f5718eaa03 * outputs/person1_step1/train_source1_country_distribution.tsv
1370ab2da7 * outputs/person1_step1/train_source1_missing_values.tsv
7a1589067d * outputs/person1_step1/train_source2_blank_values.tsv
bd1f380209 * outputs/person1_step1/train_source2_country_distribution.tsv
f842ea0bf2 * outputs/person1_step1/train_source2_missing_values.tsv
910acfe9c2 * outputs/person1_step1/train_source3_blank_values.tsv
4be8d793f3 * outputs/person1_step1/train_source3_country_distribution.tsv
45dbd03213 * outputs/person1_step1/train_source3_missing_values.tsv
----
-rw-r--r-- 1 root root 564 Sep 25 06:41 outputs/person1_step1/blocking_recall_evaluation.tsv
----
target	total_pairs	name_exact_hits	name_prefix4_hits	name_token1_hits	address_exact_hits	address_house_hits	combined_hits	name_exact_recall	name_prefix4_recall	name_token1_recall	address_exact_recall	address_house_recall	combined_recall
S2	3693619	618737	2805744	2589864	395879	2494283	3415531	16.75151118726647	75.96192243975352	70.11724815147421	10.717916493282063	67.52951509075517	92.47112384899471
S3	3944746	676346	2944171	2714716	170383	2689727	3678626	17.1454892152752	74.63524901223045	68.8185246908166	4.31923880523613	68.18504917680379	93.2538115255076

In [13]:
# ============================================================
# STEP 7A — ESTIMATE ACTUAL COMPOSITE TEST CANDIDATES
# ============================================================

import os
import duckdb

BASE = "/content/Amazon-ML-Challenge-2026"
OUT = f"{BASE}/outputs/person1_step1"
NORM = f"{OUT}/normalized"

S1 = f"{NORM}/test_source1_normalized.tsv"
S2 = f"{NORM}/test_source2_normalized.tsv"
S3 = f"{NORM}/test_source3_normalized.tsv"

DB = f"{OUT}/candidate_generation.duckdb"
TMP = f"{OUT}/candidate_generation_tmp"

os.makedirs(TMP, exist_ok=True)

db = duckdb.connect(DB)

db.execute("SET memory_limit='4GB'")
db.execute("SET threads=2")
db.execute("SET preserve_insertion_order=false")
db.execute(f"SET temp_directory='{TMP}'")

print("=" * 70)
print("STEP 7A — COMPOSITE TEST CANDIDATE VOLUME")
print("=" * 70)

# ------------------------------------------------------------
# Create compact test tables
# ------------------------------------------------------------

print("\nLoading S1 / S2 / S3...")

for name, path in [("s1", S1), ("s2", S2), ("s3", S3)]:

    db.execute(f"""
        CREATE OR REPLACE TABLE {name} AS
        SELECT
            entity_id,
            business_name,
            business_address,
            country,

            LEFT(TRIM(business_name), 4) AS p4,
            LEFT(TRIM(business_name), 5) AS p5,

            regexp_extract(
                TRIM(business_address),
                '[0-9]+[A-Za-z]?',
                0
            ) AS house

        FROM read_csv(
            '{path}',
            delim='\\t',
            header=true,
            all_varchar=true
        )
    """)

print("Tables ready.")


# ------------------------------------------------------------
# Count composite blocks
#
# IMPORTANT:
# This counts candidates but DOES NOT write them.
# ------------------------------------------------------------

def estimate(target):

    print("\n" + "=" * 70)
    print(f"S1 -> {target}")
    print("=" * 70)

    # Main selective block
    print("\n1. country + prefix5 + house")

    r = db.execute(f"""
        SELECT COUNT(*)
        FROM s1 a
        INNER JOIN {target} b
        ON
            a.country <> ''
            AND a.country = b.country
            AND a.p5 <> ''
            AND a.p5 = b.p5
            AND a.house <> ''
            AND a.house = b.house
    """).fetchone()[0]

    print(f"Candidate pairs: {r:,}")


    # Prefix4 version
    print("\n2. country + prefix4 + house")

    r2 = db.execute(f"""
        SELECT COUNT(*)
        FROM s1 a
        INNER JOIN {target} b
        ON
            a.country <> ''
            AND a.country = b.country
            AND a.p4 <> ''
            AND a.p4 = b.p4
            AND a.house <> ''
            AND a.house = b.house
    """).fetchone()[0]

    print(f"Candidate pairs: {r2:,}")


    # Exact name + country
    print("\n3. country + exact name")

    r3 = db.execute(f"""
        SELECT COUNT(*)
        FROM s1 a
        INNER JOIN {target} b
        ON
            a.country <> ''
            AND a.country = b.country
            AND TRIM(a.business_name) <> ''
            AND TRIM(a.business_name) = TRIM(b.business_name)
    """).fetchone()[0]

    print(f"Candidate pairs: {r3:,}")


    # Exact address + country
    print("\n4. country + exact address")

    r4 = db.execute(f"""
        SELECT COUNT(*)
        FROM s1 a
        INNER JOIN {target} b
        ON
            a.country <> ''
            AND a.country = b.country
            AND TRIM(a.business_address) <> ''
            AND TRIM(a.business_address) = TRIM(b.business_address)
    """).fetchone()[0]

    print(f"Candidate pairs: {r4:,}")

    return {
        "prefix5_house_country": r,
        "prefix4_house_country": r2,
        "exact_name_country": r3,
        "exact_address_country": r4
    }


s2_counts = estimate("s2")
s3_counts = estimate("s3")


print("\n" + "=" * 70)
print("FINAL VOLUME ESTIMATE")
print("=" * 70)

print("\nS1 -> S2")
for k, v in s2_counts.items():
    print(f"{k:30s}: {v:,}")

print("\nS1 -> S3")
for k, v in s3_counts.items():
    print(f"{k:30s}: {v:,}")

print("\nNo candidate files have been generated yet.")
print("This cell only measured the candidate volume.")

======================================================================
STEP 7A — COMPOSITE TEST CANDIDATE VOLUME
======================================================================

Loading S1 / S2 / S3...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Tables ready.

======================================================================
S1 -> s2
======================================================================

1. country + prefix5 + house

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 21,153,470

2. country + prefix4 + house

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 25,887,875

3. country + exact name

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 4,163,604

4. country + exact address

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 358,442

======================================================================
S1 -> s3
======================================================================

1. country + prefix5 + house

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 24,705,707

2. country + prefix4 + house

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 30,598,998

3. country + exact name

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 4,886,010

4. country + exact address

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs: 227,731

======================================================================
FINAL VOLUME ESTIMATE
======================================================================

S1 -> S2
prefix5_house_country         : 21,153,470
prefix4_house_country         : 25,887,875
exact_name_country            : 4,163,604
exact_address_country         : 358,442

S1 -> S3
prefix5_house_country         : 24,705,707
prefix4_house_country         : 30,598,998
exact_name_country            : 4,886,010
exact_address_country         : 227,731

No candidate files have been generated yet.
This cell only measured the candidate volume.